# These options apply to how the script will operate.
script_options:
  # Switch between testnet and mainnet
  # Setting this to False will use REAL funds, use at your own risk
  TEST_MODE: False

  #Fresh start: clean all historical records on start
  CLEAN_START: True

  LOG_TRADES: True
  LOG_FILE: 'trades.txt'
  DEBUG: True

  # Set this to true if you are accessing binance from within the United States of America
  # Need to change TLD
  AMERICAN_USER: False


# These options apply to data collection service
data_options:
  DB_TRANSACTIONS_FILE_NAME: transactions.db
  DB_TYPE: POSTGRES #SQLITE
  POSTGRESS_HOST: postgres_server #local_host
  POSTGRESS_PORT: 5432
  POSTGRESS_DB: candles
  POSTGRES_USER: postgres
  POSTGRES_PASS: postgres
  INIT_START: True
  INTERVAL: 1m
  INIT_PERIOD: 201 hours ago UTC
  DB_TRANSACTIONS_FILE_NAME: transactions.db
  DB_CANDLE_FILE_NAME: candles.db
  DB_STUDY_FILE_NAME: study.db

# These options apply to the trading methods the script executes
trading_options:
  # select your base currency to use for trading (trade for example USDT pairs)
  PAIR_WITH: USDTM

  # select your leverage
  LEVERAGE: 20

  # Total amount per trade (your base currency balance must be at least TRADE_SLOTS * TRADE_TOTAL)
  # Recommended: no less than 12 USDT. Suggested: 15 or more.
  TRADE_TOTAL: 50
  


  # Maximum number of trade 'slots' at any time (your USDT balance must be at least TRADE_SLOTS * TRADE_TOTAL)
  TRADE_SLOTS: 1


  # List of trading pairs to exclude
  # by default we're excluding the most popular fiat pairs
  FIATS:
    - EURUSDTM
    - GBPUSDTM
    - JPYUSDTM
    - USDUSDTM
    - AUDUSDTM
    - DOWNM
    - UPM
    - BUSDUSDTM

  # EX_PAIRS is value list of fiat currencies and margin symbols that I am excluding.
  # Anything added here will be excluded from coin withdrawal and will not be sold.
  EX_PAIRS: ['EUR', 'USD', 'GBP', 'USDT', 'AUD', 'BRL', 'RUB', 'TRY', 'USDC', 'PAX', 'BIDR', 'DAI', 'IDRT',
  'UAH', 'NGN', 'VAI', 'BVND', 'JPY', 'NCASH', 'UPUSDT', 'DOWNUSDT', 'USDTUP', 'USDTDOWN', 'BNBDOWN',
  'EOSDOWN', 'XLMDOWN', 'UNIDOWN', 'LINKDOWN', 'FILDOWN', 'TRXDOWN', 'XRPDOWN', 'AAVEDOWN', 'SUSHIDOWN',
  'XTZDOWN', 'ADADOWN', '1INCHDOWN', 'BTCDOWN', 'SXPDOWN', 'DOTDOWN', 'ETHDOWN', 'BCHDOWN', 'LTCDOWN',
  'YFIDOWN', 'XTZUP', 'DOTUP', 'ADAUP', 'SUPER', 'AAVEUP', 'BTCUP', 'BNBUP', 'SXPUP', 'YFIUP', 'XLMUP',
  'UNIUP', 'FILUP', '1INCHUP', 'LINKUP', 'LTCUP', 'ETHUP', 'SUSHIUP', 'EOSUP', 'XRPUP', 'TRXUP', 'BCHUP',
  'RENBTC', 'B']


  # the amount of time in MINUTES to calculate the difference from the current price (minimum: 1).
  TIME_DIFFERENCE: 1

  # Number of times to check for TP/SL during each TIME_DIFFERENCE (minimum: 1).
  # Don't spam the Binance API, you will be banned (max 1200 requests per minute per IP).
  RECHECK_INTERVAL: 6 #1

  # the difference in % between the first and second checks for the price. 100 will disable volatility gain buying
  CHANGE_IN_PRICE: 100 #0.01

  # define in % when to sell value coin that's not making value profit.
  STOP_LOSS: 20

  # define in % when to take profit on value profitable coin.
  TAKE_PROFIT: 30

  # Use custom tickers.txt list for filtering pairs.
  CUSTOM_LIST: False
  # Whether to automatically reload the custom tickers list
  CUSTOM_LIST_AUTORELOAD: False
  # Name of custom tickers list
  TICKERS_LIST: 'tickerlists/tickers_kucoin_USDT.txt'
#  TICKERS_LIST: 'tickerlists/tickers_all_withUSDT.txt'
#  TICKERS_LIST: 'tickers_all_USDT.txt'
#  TICKERS_LIST: 'tickerlists/tickers_top40.txt'

   # whether to use trailing stop loss or not; default is True
  # when hit TAKE_PROFIT, move STOP_LOSS to TRAILING_STOP_LOSS percentage points below TAKE_PROFIT hence locking in profit
  # when hit TAKE_PROFIT, move TAKE_PROFIT up by TRAILING_TAKE_PROFIT percentage points
  # NOTE -SELL_ON_SIGNAL_ONLY will override USE_TRAILING_STOP_LOSS
  USE_TRAILING_STOP_LOSS: False
  TRAILING_STOP_LOSS: 0.2 #0.1
  TRAILING_TAKE_PROFIT: .05

  # Let value signalling module control sell of coin
  # NOTE - If USE_TRAILING_STOP_LOSS: True then this needs to be False
  SELL_ON_SIGNAL_ONLY: False

  # Trading fee in % per trade.
  # If using 0.075% (using BNB for fees) you must have BNB in your account to cover trading fees.
  # If using BNB for fees, it MUST be enabled in your Binance 'Dashboard' page (checkbox).
  TRADING_FEE: 0.006 # 0.006 kucoin

  # Discord integration
  # Used to push alerts, messages etc to value discord channel
  MSG_DISCORD: True
  
  REINVEST_PROFITS: True

  #Enables the use of currencies with greater or lesser volume
  USE_MOST_VOLUME_COINS: False
  #idea from my psychologist, thanks Sebastian V.
  COINS_MAX_VOLUME: 5000000000
  COINS_MIN_VOLUME: 100000000

  SIGNALLING_MODULES:
    # NOTE: Only use the "os_xxxxxxxxx" or "nigec_xxxxxxxxx" etc signal/pause modules with this fork as 
    # the default ones WILL NOT work due to customisations for my specific purposes
    #
#    - pausebotmod
#    - os_pausebot_MAv2
    - import_kucoin_tickers
#    - os_signalbuy_RECOMM
#    - rs_wavetrend
#    - rs_nwe
#    - rs_polynomial
#    - nigec_signalbuy_RSI
#    - os_signalbuy_3SMAv2
#    - djcommie_signalbuy_rsi_stoch
#    - signalsamplemod
#    - os_signals_buy_3st
#    - rsi-mod
#    - nigec_signalsell_RSI
#    - os_signalsell_RECOMM
#    - os_signalsell_3SMAv2
#    - djcommie_signalsell_rsi_stoch
#    - vyacheslav_signalbuy_VolScan
#    - the_snail

  
